### ISSUE TITLE
`spec/support/shared_examples/` doesn't work

### ISSUE THREAD

**Issue by bioform** [rubyatscale/packs-rails#59]
If you try to put any spec shared example file to the `spec/support/shared_examples/` pack-related folder, it will be unavailable for package-related specs.
The resulting error looks like this:
```
ArgumentError:
  Could not find shared examples "shared example name"
```

**Comment by alexevanczuk** [comment]
@bioform Going to close this for now – please let me know if you have any questions/concerns/feedback and we can reopen this.
