### ISSUE TITLE
Modulize packs

### ISSUE THREAD

**Issue by LuukvH** [rubyatscale/packs-rails#67]
This might be more of a question is it possible to have everything in a pack modulized. Without creating the nested folders for example:

```file
- Packages
  └ Sales
     |- App
     │  ├─ models
     │  │        └ Lead.rb
     │  └─ Controllers
```

And lead is modulized as shown below.
```ruby
module Sales
 class Lead
 end
end
```
I know its possible to change the file structure however i don't like have even deeper nesting of folders for autoloading to pick this up.

**Comment by alexevanczuk** [comment]
Yes this is possible! Try this: https://github.com/gap777/automatic_namespaces
