### ISSUE TITLE
Add Rubocop

### ISSUE THREAD

**Issue by schoblaska** [rubyatscale/packs-rails#95]
* [ ] Grab a `.rubocop.yml` file from an existing @rubyatscale repo
* [ ] Fix violations
* [ ] Add a [step](https://github.com/rubyatscale/shared-config/blob/e3e4fb03f0cb52b09138d3a17a04bd60601bf50f/.github/workflows/ci.yml#L40-L51) to the CI workflow that runs Rubocop

This repo embeds [two Rails apps](https://github.com/rubyatscale/packs-rails/tree/825e6b4240767a40f97449376c01572bce2cf09d/spec/fixtures) for testing. The Rubocop rules can ignore those directories.

**Comment by tstannard** [comment]
Commenting to keep this open
